#!/usr/bin/env bash
# Prépare la vidéo du hero d'accueil (components/HeroVideo.vue) à partir de la
# vidéo brute générée avec MiniMax H3 :
#   - hero.web.mp4     : recompressée. La brute pèse 9 Mo à 7 Mb/s, beaucoup pour la
#                        première chose que charge la page ; crf 31 la divise par
#                        plusieurs sans perte visible à l'échelle d'un écran ;
#   - hero-poster.jpg  : une image fixe, affichée le temps que la vidéo arrive, et en
#                        continu pour qui a demandé moins de mouvement.
#
# Usage (depuis la racine du dépôt) :
#   scripts/hero-video.sh                       # la vidéo brute par défaut
#   scripts/hero-video.sh chemin/vers/brute.mp4
#
# Variable optionnelle : START_FRAME=0 pour garder toutes les images.
#
# Requiert ffmpeg. Si la vidéo change (une nouvelle génération, sans filigrane...),
# la relancer, puis ajuster RATIO dans components/HeroVideo.vue si le format change.
set -euo pipefail

SRC="${1:-components/minimaxH3/hero/lumea_animation.mp4}"
DIR="$(dirname "$SRC")"

# Images à sauter au début. L'ancienne vidéo brute portait le filigrane « Generated by
# MiniMax AI » sur ses 14 premières images (START_FRAME était alors à 15) ;
# lumea_animation.mp4 n'en a aucun (vérifié dans les coins, au début, au milieu et à
# la fin) : on garde tout. À revérifier à chaque nouvelle vidéo brute.
START_FRAME="${START_FRAME:-0}"

# Pas de piste audio (-an) : la vidéo est muette, et c'est ce qui autorise la lecture
# automatique dans tous les navigateurs. +faststart : la lecture peut commencer avant
# la fin du téléchargement.
ffmpeg -v error -y -i "$SRC" \
  -vf "trim=start_frame=${START_FRAME},setpts=PTS-STARTPTS" \
  -c:v libx264 -preset slow -crf 31 -pix_fmt yuv420p \
  -movflags +faststart -an "$DIR/hero.web.mp4"

# L'image d'attente est la première de la version web (et non une image prise plus loin) :
# quand la vidéo démarre, elle prend la place du poster sans à-coup.
ffmpeg -v error -y -i "$DIR/hero.web.mp4" -frames:v 1 -q:v 3 "$DIR/hero-poster.jpg"

ls -l "$DIR/hero.web.mp4" "$DIR/hero-poster.jpg" | awk '{ printf "%-45s %.2f Mo\n", $NF, $5 / 1e6 }'
