#!/usr/bin/env bash
# Prépare la vidéo du menu (le personnage qui écrit « MENU » à la craie, généré avec
# MiniMax H3) pour components/NavOverlay.vue.
#
# Contrairement aux autres vidéos MiniMax du projet, le filigrane « Generated by
# MiniMax AI » n'est pas limité aux premières images ici : il est présent sur les
# 141 images de la vidéo, dans le même coin bas-droit à chaque fois, sur un fond
# resté uniformément noir pur (0,0,0) à cet endroit sur toute la vidéo (vérifié
# image par image : le personnage n'y entre jamais). On peint donc un rectangle
# noir dessus (drawbox) plutôt que de rogner des images comme pour le hero ou la
# bouteille — un rognage aurait coupé les pieds du personnage, qui descendent
# jusque dans la bande du filigrane sur la partie gauche du cadre.
#
# À revoir avec les conditions d'utilisation de la formule MiniMax utilisée ; la
# vraie solution est de générer la vidéo sans filigrane.
#
# Usage (depuis la racine du dépôt) :
#   scripts/menu-video.sh
#   scripts/menu-video.sh chemin/vers/brute.mp4
set -euo pipefail

SRC="${1:-components/minimaxH3/menu/444429349318876.mp4}"
DIR="$(dirname "$SRC")"

# Rectangle du filigrane, mesuré sur la vidéo source (1934 x 1080) : x 1315..1914,
# y 1012..1063. Celui-ci va jusqu'aux bords du cadre, avec de la marge.
WM="x=1300:y=1000:w=634:h=80:color=black:t=fill"

ffmpeg -v error -y -i "$SRC" \
  -vf "drawbox=${WM}" \
  -c:v libx264 -preset slow -crf 27 -pix_fmt yuv420p \
  -movflags +faststart -an "$DIR/menu.web.mp4"

# L'image d'attente est prise juste après la fin du mot (le personnage a fini d'écrire,
# sa main se retire) : c'est l'image la plus satisfaisante à voir seule, pour qui a
# demandé moins de mouvement (elle reste alors affichée en permanence, la vidéo n'étant
# jamais lue).
ffmpeg -v error -y -ss 5.3 -i "$DIR/menu.web.mp4" -frames:v 1 -q:v 3 "$DIR/menu-poster.jpg"

ls -l "$DIR/menu.web.mp4" "$DIR/menu-poster.jpg" | awk '{ printf "%-40s %.2f Mo\n", $NF, $5 / 1e6 }'
