#!/usr/bin/env python3
"""
Détoure la vidéo de la course des fruits (fond de studio blanc -> transparent)
et l'écrit en « alpha empilé » : un .mp4 classique dont la moitié haute porte la
couleur et la moitié basse le masque de transparence (en niveaux de gris).

Pourquoi : aucun navigateur ne lit d'alpha dans un .mp4, et WebM/HEVC alpha ne
couvrent pas tous les navigateurs. En revanche tous lisent un .mp4 H.264, et
FooterSprint.vue recompose couleur + alpha dans un shader WebGL.

Usage (depuis la racine du dépôt) :
    pip install numpy scipy
    python3 scripts/sprint-alpha.py
    python3 scripts/sprint-alpha.py entree.mp4 sortie.mp4

Requiert ffmpeg dans le PATH. Compter environ une minute pour 6 secondes de vidéo.

Si vous changez de vidéo (un autre cadrage, une nouvelle génération sans
filigrane...), ajustez CROP et FLOOR_Y ci-dessous, puis les dimensions
correspondantes dans components/FooterSprint.vue (constante SIZE).
"""
import subprocess
import sys
from pathlib import Path

import numpy as np
from scipy import ndimage as ndi

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_IN = ROOT / "components/minimaxH3/fruit-sprint-footer.mp4"
DEFAULT_OUT = ROOT / "components/minimaxH3/fruit-sprint-footer.alpha.mp4"

# Cadrage sur les trois personnages, en pixels de la vidéo d'origine (1934 x 1080).
# Le bas tombe juste sous les pieds et leurs ombres : le sol vide, et le filigrane
# « Generated by MiniMax AI » qui s'y trouve, restent hors champ.
CROP = {"x": 150, "y": 220, "w": 1650, "h": 660}

# Dans le cadrage, à partir de cette ligne on est dans la bande du sol : ce qui est
# clair et pâle y est de l'ombre, pas un fruit. Au-dessus, ce sont les fruits.
FLOOR_Y = 560

FPS = 24

# Taille livrée : le détourage se fait sur le cadrage entier, puis la vidéo est
# réduite à cette largeur avant l'encodage. 1320 px suffisent pour un affichage à
# 1080 px de large ; à 2 Mo on reste léger, sans perte visible de netteté.
OUT_W = 1320
OUT_H = round(OUT_W * CROP["h"] / CROP["w"])   # 528 : couleur, puis alpha en dessous
CRF = 28

# De combien de pixels on épaissit les bordures avant de chercher ce qui touche le bord
# du cadre. Un œil au bord du visage n'est séparé du fond que par un liséré de
# quelques pixels, aux points parfois trop pâles pour compter comme une bordure : le
# fond fuit alors dans l'œil, qui devient transparent. Épaissir bouche ces brèches
# (jusqu'à environ 2 x SEAL pixels).
SEAL = 3

# Jusqu'où les couleurs du bord sont prolongées dans la zone transparente, en pixels.
EXTEND_PX = 8


def matte(rgb: np.ndarray):
    """rgb : float32 (H, W, 3) entre 0 et 1  ->  (couleur droite, alpha), même forme."""
    mx, mn = rgb.max(axis=2), rgb.min(axis=2)
    sat = np.where(mx > 0, (mx - mn) / np.maximum(mx, 1e-6), 0)
    lum = rgb @ np.array([0.299, 0.587, 0.114], dtype=np.float32)

    # 1. Ce qui ressemble au fond : peu saturé et clair. Les ombres au sol sont
    #    teintées (rose sous la fraise, beige sous la banane) : dans la bande du
    #    sol, on est plus tolérant.
    bglike = (sat < 0.10) & (lum > 0.50)
    yy = np.arange(rgb.shape[0])[:, None]
    bglike |= (yy > FLOOR_Y) & (sat < 0.45) & (lum > 0.35)

    # 2. Le fond est ce qui touche le bord du cadre. Le reste est premier plan :
    #    c'est ce qui garde les yeux blancs, enfermés dans le visage, opaques.
    #    Les bordures sont d'abord épaissies (SEAL), pour que le fond ne fuie pas dans
    #    un œil par une brèche de son liséré ; on regagne ensuite ces pixels.
    barrier = ndi.binary_dilation(~bglike, iterations=SEAL)
    labels, _ = ndi.label(bglike & ~barrier)  # connexité 4 : un trait fin sépare deux zones
    edge = np.concatenate([labels[0], labels[-1], labels[:, 0], labels[:, -1]])
    core = np.isin(labels, np.unique(edge[edge > 0]))
    bg = ndi.binary_dilation(core, iterations=SEAL) & bglike
    fg = ~bg

    # Les îlots de bruit, loin des personnages, ne sont pas des personnages.
    lab, n = ndi.label(fg)
    if n:
        sizes = ndi.sum(fg, lab, range(1, n + 1))
        fg = np.isin(lab, [i + 1 for i, s in enumerate(sizes) if s > 2500])

    # 3. Bord : on grignote 1 px (le liséré blanc hérité du fond), puis on adoucit.
    a_fg = ndi.gaussian_filter(ndi.binary_erosion(fg, iterations=1).astype(np.float32), 0.9)

    # 4. Fond et ombres : « couleur vers alpha » contre un fond local estimé. Le
    #    fond de studio est plus sombre vers les bords ; on prend l'enveloppe claire
    #    des pixels de fond alentour, sans les ombres (plus petites que la fenêtre).
    away = (~ndi.binary_dilation(fg, iterations=3))[..., None]
    B = ndi.maximum_filter(np.where(away, rgb, 0), size=(61, 61, 1))
    B = np.maximum(ndi.gaussian_filter(B, (15, 15, 0)), 0.6)
    a_bg = np.clip((1 - np.clip(rgb / B, 0, 1).min(axis=2)) - 0.03, 0, 1) / 0.97
    a_bg = np.clip(a_bg * 1.15, 0, 1)
    f_bg = np.clip((rgb - (1 - a_bg[..., None]) * B) / np.maximum(a_bg[..., None], 1e-3), 0, 1)

    # 5. Assemblage : alpha, puis couleur « droite » (non prémultipliée).
    a = a_fg + (1 - a_fg) * a_bg
    premult = a_fg[..., None] * rgb + ((1 - a_fg) * a_bg)[..., None] * f_bg
    color = np.where(a[..., None] > 1e-3, premult / np.maximum(a[..., None], 1e-3), 0)
    color = np.clip(color, 0, 1)

    # 6. Les zones transparentes prennent la couleur du pixel opaque le plus proche,
    #    sur quelques pixels seulement : la compression vidéo ne mélange alors pas de
    #    noir ou de blanc aux bords. Plus loin, un gris uni : des traînées de couleur
    #    étirées sur tout le fond coûteraient cher à encoder pour rien.
    dist, (iy, ix) = ndi.distance_transform_edt(~(a > 0.5), return_indices=True)
    fill = np.where((dist < EXTEND_PX)[..., None], color[iy, ix], 0.5)
    color = np.where((a > 0.02)[..., None], color, fill)
    return color, a


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IN
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    w, h = CROP["w"], CROP["h"]
    frame_bytes = w * h * 3

    decode = subprocess.Popen(
        ["ffmpeg", "-v", "error", "-i", str(src),
         "-vf", f"crop={w}:{h}:{CROP['x']}:{CROP['y']}",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
        stdout=subprocess.PIPE,
    )
    encode = subprocess.Popen(
        ["ffmpeg", "-v", "error", "-y",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{w}x{h * 2}", "-r", str(FPS), "-i", "-",
         "-vf", f"scale={OUT_W}:{OUT_H * 2}:flags=lanczos,scale=out_color_matrix=bt709:out_range=tv,format=yuv420p",
         "-c:v", "libx264", "-preset", "slow", "-crf", str(CRF),
         "-colorspace", "bt709", "-color_primaries", "bt709", "-color_trc", "bt709", "-color_range", "tv",
         "-movflags", "+faststart", "-an", str(dst)],
        stdin=subprocess.PIPE,
    )

    count = 0
    while True:
        raw = decode.stdout.read(frame_bytes)
        if len(raw) < frame_bytes:
            break
        rgb = np.frombuffer(raw, dtype=np.uint8).reshape(h, w, 3).astype(np.float32) / 255
        color, alpha = matte(rgb)
        packed = np.empty((h * 2, w, 3), dtype=np.uint8)
        packed[:h] = (color * 255 + 0.5).astype(np.uint8)
        packed[h:] = (alpha[..., None] * 255 + 0.5).astype(np.uint8)  # gris : R = G = B
        encode.stdin.write(packed.tobytes())
        count += 1
        if count % 20 == 0:
            print(f"  {count} images", flush=True)

    encode.stdin.close()
    encode.wait()
    decode.wait()
    print(f"{count} images -> {dst} ({dst.stat().st_size / 1e6:.2f} Mo)")


if __name__ == "__main__":
    main()
